server:
  port: 8082
spring:
  application:
    name: "report"
  webflux:
    base-path: "/"
  devtools:
    livereload:
      enabled: false
  profiles:
    active: "local"
logging:
  level:
    co.com.pragma: "DEBUG"
    org.springframework.web: "DEBUG"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
routes:
  paths:
    global: "/api/v1"
aws:
  dynamodb:
    endpoint: "${AWS_DYNAMO_DB_ENDPOINT:https://dynamodb.us-east-1.amazonaws.com}"
    accessKey: "${AWS_ACCESS_KEY:any}"
    secretKey: "${AWS_SECRET_KEY:any}"
  region: "${AWS_REGION:us-east-1}"
adapter:
  sqs:
    region: "us-east-1"
    queueUrl: "${SQS_SENDER_URL:https://sqs.us-east-1.amazonaws.com/225685253174/sqs_report_sender_to_ms}"
    # endpoint: "http://localhost:4566 # For localstack only"
ms-authentication:
  base-url: "${AUTHENTICATION_BASE_URL:http://localhost:8080}"
  jwt-secret-key: "${APP_SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}"
  jwt-expiration: "${APP_EXP_TIME:3600000}"
entrypoint:
  sqs:
    region: "us-east-1"
    # endpoint: "http://localhost:4566"
    queueUrl: "${SQS_LISTENER_URL:https://sqs.us-east-1.amazonaws.com/225685253174/sqs_update_report}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
